//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopClient.FrontEndWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/FrontEndWCFService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrontEndWcfService.IFrontEndService")]
    public interface IFrontEndService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetAreaOfCircle", ReplyAction="http://tempuri.org/IFrontEndService/GetAreaOfCircleResponse")]
        string GetAreaOfCircle(string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetAreaOfCircle", ReplyAction="http://tempuri.org/IFrontEndService/GetAreaOfCircleResponse")]
        System.Threading.Tasks.Task<string> GetAreaOfCircleAsync(string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetAreaOfCircle2", ReplyAction="http://tempuri.org/IFrontEndService/GetAreaOfCircle2Response")]
        string GetAreaOfCircle2(string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetAreaOfCircle2", ReplyAction="http://tempuri.org/IFrontEndService/GetAreaOfCircle2Response")]
        System.Threading.Tasks.Task<string> GetAreaOfCircle2Async(string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFrontEndService/GetDataUsingDataContractResponse")]
        DesktopClient.FrontEndWcfService.CompositeType GetDataUsingDataContract(DesktopClient.FrontEndWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFrontEndService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<DesktopClient.FrontEndWcfService.CompositeType> GetDataUsingDataContractAsync(DesktopClient.FrontEndWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetActivityRootId", ReplyAction="http://tempuri.org/IFrontEndService/GetActivityRootIdResponse")]
        string GetActivityRootId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetActivityRootId", ReplyAction="http://tempuri.org/IFrontEndService/GetActivityRootIdResponse")]
        System.Threading.Tasks.Task<string> GetActivityRootIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetActivityRootId2Hop", ReplyAction="http://tempuri.org/IFrontEndService/GetActivityRootId2HopResponse")]
        string GetActivityRootId2Hop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetActivityRootId2Hop", ReplyAction="http://tempuri.org/IFrontEndService/GetActivityRootId2HopResponse")]
        System.Threading.Tasks.Task<string> GetActivityRootId2HopAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFrontEndServiceChannel : DesktopClient.FrontEndWcfService.IFrontEndService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontEndServiceClient : System.ServiceModel.ClientBase<DesktopClient.FrontEndWcfService.IFrontEndService>, DesktopClient.FrontEndWcfService.IFrontEndService {
        
        public FrontEndServiceClient() {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontEndServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAreaOfCircle(string radius) {
            return base.Channel.GetAreaOfCircle(radius);
        }
        
        public System.Threading.Tasks.Task<string> GetAreaOfCircleAsync(string radius) {
            return base.Channel.GetAreaOfCircleAsync(radius);
        }
        
        public string GetAreaOfCircle2(string radius) {
            return base.Channel.GetAreaOfCircle2(radius);
        }
        
        public System.Threading.Tasks.Task<string> GetAreaOfCircle2Async(string radius) {
            return base.Channel.GetAreaOfCircle2Async(radius);
        }
        
        public DesktopClient.FrontEndWcfService.CompositeType GetDataUsingDataContract(DesktopClient.FrontEndWcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<DesktopClient.FrontEndWcfService.CompositeType> GetDataUsingDataContractAsync(DesktopClient.FrontEndWcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string GetActivityRootId() {
            return base.Channel.GetActivityRootId();
        }
        
        public System.Threading.Tasks.Task<string> GetActivityRootIdAsync() {
            return base.Channel.GetActivityRootIdAsync();
        }
        
        public string GetActivityRootId2Hop() {
            return base.Channel.GetActivityRootId2Hop();
        }
        
        public System.Threading.Tasks.Task<string> GetActivityRootId2HopAsync() {
            return base.Channel.GetActivityRootId2HopAsync();
        }
    }
}
